Repository SeungHyunLee054/NewsFeeds-spring, pull requests merged in 2025-04, with the labels that each got.

#9 Feature : 공통 응답
  src/main/java/com/nbc/newsfeeds/common/response/CommonResponse.java
  src/main/java/com/nbc/newsfeeds/common/response/CommonResponses.java
  src/main/java/com/nbc/newsfeeds/common/response/ResponseCode.java
Labels: enhancement

#8 Featrue : 친구 심화 기능
  src/main/java/com/nbc/newsfeeds/domain/friend/constant/FriendshipStatus.java
  src/main/java/com/nbc/newsfeeds/domain/friend/controller/FriendController.java
  src/main/java/com/nbc/newsfeeds/domain/friend/entity/Friendship.java
  src/main/java/com/nbc/newsfeeds/domain/friend/entity/FriendshipStatus.java
  src/main/java/com/nbc/newsfeeds/domain/friend/model/request/CursorPageRequest.java
  src/main/java/com/nbc/newsfeeds/domain/friend/model/request/RespondToFriendRequest.java
  src/main/java/com/nbc/newsfeeds/domain/friend/model/response/CursorPage.java
  src/main/java/com/nbc/newsfeeds/domain/friend/model/response/FriendRequestResponse.java
  src/main/java/com/nbc/newsfeeds/domain/friend/model/response/FriendRequestsResponse.java
  src/main/java/com/nbc/newsfeeds/domain/friend/model/response/FriendsResponse.java
  src/main/java/com/nbc/newsfeeds/domain/friend/repository/FriendshipRepository.java
  src/main/java/com/nbc/newsfeeds/domain/friend/service/FriendService.java
Labels: enhancement

#11 Feature : 예외 처리
  src/main/java/com/nbc/newsfeeds/common/exception/BaseException.java
  src/main/java/com/nbc/newsfeeds/common/exception/dto/ValidationError.java
  src/main/java/com/nbc/newsfeeds/common/exception/handler/GlobalExceptionHandler.java
Labels: enhancement

#15 Feature : 친구 - 임시 코드 -> 실제 로직으로 전환
  src/main/java/com/nbc/newsfeeds/common/exception/BizException.java
  src/main/java/com/nbc/newsfeeds/domain/friend/controller/FriendController.java
  src/main/java/com/nbc/newsfeeds/domain/friend/entity/Friendship.java
  src/main/java/com/nbc/newsfeeds/domain/friend/exception/FriendExceptionCode.java
  src/main/java/com/nbc/newsfeeds/domain/friend/model/request/CursorPageRequest.java
  src/main/java/com/nbc/newsfeeds/domain/friend/repository/FriendshipRepository.java
  src/main/java/com/nbc/newsfeeds/domain/friend/service/FriendService.java
Labels: enhancement

#16 Fix : jwt 토큰 권한
  src/main/java/com/nbc/newsfeeds/common/jwt/JwtTokenProvider.java
  src/main/java/com/nbc/newsfeeds/common/jwt/constant/JwtConstants.java
  src/main/java/com/nbc/newsfeeds/domain/member/dto/MemberAuthDto.java
  src/main/java/com/nbc/newsfeeds/domain/member/entity/Member.java
  src/main/java/com/nbc/newsfeeds/domain/member/service/MemberService.java
Labels: bug

#22 Refactor : 친구 서비스 리팩토링
  src/main/java/com/nbc/newsfeeds/common/response/CommonResponse.java
  src/main/java/com/nbc/newsfeeds/domain/friend/controller/FriendControllerAdvice.java
  src/main/java/com/nbc/newsfeeds/domain/friend/entity/Friendship.java
  src/main/java/com/nbc/newsfeeds/domain/friend/exception/FriendExceptionCode.java
  src/main/java/com/nbc/newsfeeds/domain/friend/model/request/FriendRequestDecision.java
  src/main/java/com/nbc/newsfeeds/domain/friend/model/request/RespondToFriendRequest.java
  src/main/java/com/nbc/newsfeeds/domain/friend/repository/FriendshipRepository.java
  src/main/java/com/nbc/newsfeeds/domain/friend/service/FriendService.java
Labels: enhancement

#29 Test : 친구 API 테스트 코드 작성
  build.gradle
  src/main/java/com/nbc/newsfeeds/common/config/SecurityConfig.java
  src/main/java/com/nbc/newsfeeds/common/request/CursorPageRequest.java
  src/main/java/com/nbc/newsfeeds/domain/friend/controller/FriendController.java
  src/main/java/com/nbc/newsfeeds/domain/friend/exception/FriendBizException.java
  src/main/resources/application-test.properties
  src/test/java/com/nbc/newsfeeds/NewsFeedsApplicationTests.java
  src/test/java/com/nbc/newsfeeds/domain/friend/controller/FriendControllerIntegrationTest.java
  src/test/java/com/nbc/newsfeeds/domain/friend/entity/FriendshipUnitTest.java
  src/test/java/com/nbc/newsfeeds/domain/friend/service/FriendServiceUnitTest.java
  src/test/java/com/nbc/newsfeeds/domain/support/fixture/FixtureFactory.java
  src/test/java/com/nbc/newsfeeds/domain/support/security/TestAuthHelper.java
  src/test/java/com/nbc/newsfeeds/domain/support/security/TestSecurityConfig.java
Labels: enhancement

#39 Feat : 유저 수정, 프로필 조회
  src/main/java/com/nbc/newsfeeds/domain/member/constant/MemberResponseCode.java
  src/main/java/com/nbc/newsfeeds/domain/member/controller/AuthController.java
  src/main/java/com/nbc/newsfeeds/domain/member/controller/ProfileController.java
  src/main/java/com/nbc/newsfeeds/domain/member/dto/request/MemberSignUpDto.java
  src/main/java/com/nbc/newsfeeds/domain/member/dto/request/MemberUpdateDto.java
  src/main/java/com/nbc/newsfeeds/domain/member/dto/request/MemberWithdrawDto.java
  src/main/java/com/nbc/newsfeeds/domain/member/dto/response/MemberDto.java
  src/main/java/com/nbc/newsfeeds/domain/member/entity/Member.java
  src/main/java/com/nbc/newsfeeds/domain/member/service/MemberService.java
  src/test/java/com/nbc/newsfeeds/domain/member/controller/AuthControllerTest.java
  src/test/java/com/nbc/newsfeeds/domain/member/controller/ProfileControllerTest.java
  src/test/java/com/nbc/newsfeeds/domain/member/service/MemberServiceTest.java
Labels: enhancement

#45 Docs : README 작성
  README.md
Labels: documentation

#43 Feature : 친구 목록 조회 캐싱 적용, 친구 기능 주석 작성
  src/main/java/com/nbc/newsfeeds/common/redis/config/CacheTtlProperties.java
  src/main/java/com/nbc/newsfeeds/common/redis/config/RedisConfig.java
  src/main/java/com/nbc/newsfeeds/common/redis/constant/CacheNames.java
  src/main/java/com/nbc/newsfeeds/common/util/CursorPaginationUtil.java
  src/main/java/com/nbc/newsfeeds/domain/friend/controller/FriendController.java
  src/main/java/com/nbc/newsfeeds/domain/friend/repository/FriendCacheRepository.java
  src/main/java/com/nbc/newsfeeds/domain/friend/service/FriendService.java
  src/main/resources/application.properties
  src/test/java/com/nbc/newsfeeds/domain/friend/controller/FriendControllerIntegrationTest.java
  src/test/java/com/nbc/newsfeeds/domain/friend/service/FriendServiceUnitTest.java
Labels: enhancement

#52 Docs : 친구 기능 내용 설명 추가
  README.md
  src/main/java/com/nbc/newsfeeds/domain/friend/service/FriendService.java
  src/main/resources/application.properties
Labels: documentation

#57 Feature : 친구 요청, 응답 로직 수정, 친구 게시물 목록 조회 API
  src/main/java/com/nbc/newsfeeds/domain/feed/repository/FeedRepository.java
  src/main/java/com/nbc/newsfeeds/domain/feed/repository/JpaFeedRepositoryImpl.java
  src/main/java/com/nbc/newsfeeds/domain/friend/controller/FriendController.java
  src/main/java/com/nbc/newsfeeds/domain/friend/repository/FriendshipRepository.java
  src/main/java/com/nbc/newsfeeds/domain/friend/service/FriendService.java
  src/test/java/com/nbc/newsfeeds/domain/friend/controller/FriendControllerIntegrationTest.java
  src/test/java/com/nbc/newsfeeds/domain/friend/service/FriendServiceUnitTest.java
  src/test/java/com/nbc/newsfeeds/domain/support/fixture/FixtureFactory.java
  src/test/java/com/nbc/newsfeeds/domain/support/fixture/TestFixtureFactory.java
Labels: enhancement

#64 Fix : 친구 게시글 조회 버그 수정
  src/main/java/com/nbc/newsfeeds/domain/friend/repository/FriendshipRepository.java
Labels: bug

#80 Fix : 친구 게시글 조회 캐싱 로직 실수 수정
  README.md
  src/main/java/com/nbc/newsfeeds/common/constant/CursorPageConst.java
  src/main/java/com/nbc/newsfeeds/common/exception/BaseException.java
  src/main/java/com/nbc/newsfeeds/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/nbc/newsfeeds/common/filter/JwtExceptionFilter.java
  src/main/java/com/nbc/newsfeeds/common/filter/exception/FilterExceptionCode.java
  src/main/java/com/nbc/newsfeeds/common/jwt/exception/JwtTokenExceptionCode.java
  src/main/java/com/nbc/newsfeeds/common/model/request/CursorPageRequest.java
  src/main/java/com/nbc/newsfeeds/common/model/response/CommonResponse.java
  src/main/java/com/nbc/newsfeeds/common/model/response/CommonResponses.java
  src/main/java/com/nbc/newsfeeds/common/model/response/CursorPage.java
  src/main/java/com/nbc/newsfeeds/common/model/response/CursorPageResponse.java
  src/main/java/com/nbc/newsfeeds/common/model/response/ResponseCode.java
  src/main/java/com/nbc/newsfeeds/common/redis/config/RedisConfig.java
  src/main/java/com/nbc/newsfeeds/common/redis/exception/RedisException.java
  src/main/java/com/nbc/newsfeeds/common/redis/exception/RedisTokenResponseCode.java
  src/main/java/com/nbc/newsfeeds/common/util/CursorPaginationUtil.java
  src/main/java/com/nbc/newsfeeds/domain/comment/code/CommentExceptionCode.java
  src/main/java/com/nbc/newsfeeds/domain/comment/code/CommentSuccessCode.java
  src/main/java/com/nbc/newsfeeds/domain/comment/controller/CommentController.java
  src/main/java/com/nbc/newsfeeds/domain/comment/exception/CommentException.java
  src/main/java/com/nbc/newsfeeds/domain/comment/service/CommentService.java
  src/main/java/com/nbc/newsfeeds/domain/feed/code/FeedExceptionCode.java
  src/main/java/com/nbc/newsfeeds/domain/feed/code/FeedSuccessCode.java
  src/main/java/com/nbc/newsfeeds/domain/feed/controller/FeedController.java
  src/main/java/com/nbc/newsfeeds/domain/feed/dto/FeedSearchCondition.java
  src/main/java/com/nbc/newsfeeds/domain/feed/exception/FeedBizException.java
  src/main/java/com/nbc/newsfeeds/domain/feed/service/FeedService.java
  src/main/java/com/nbc/newsfeeds/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/nbc/newsfeeds/domain/friend/controller/FriendController.java
  src/main/java/com/nbc/newsfeeds/domain/friend/controller/FriendControllerAdvice.java
  src/main/java/com/nbc/newsfeeds/domain/friend/exception/FriendExceptionCode.java
  src/main/java/com/nbc/newsfeeds/domain/friend/repository/FriendCacheRepository.java
  src/main/java/com/nbc/newsfeeds/domain/friend/service/FriendService.java
  src/main/java/com/nbc/newsfeeds/domain/heart/controller/HeartController.java
  src/main/java/com/nbc/newsfeeds/domain/heart/dto/HeartResponseCode.java
  src/main/java/com/nbc/newsfeeds/domain/heart/exception/HeartException.java
  src/main/java/com/nbc/newsfeeds/domain/heart/exception/HeartExceptionCode.java
  src/main/java/com/nbc/newsfeeds/domain/member/constant/MemberResponseCode.java
  src/main/java/com/nbc/newsfeeds/domain/member/controller/AuthController.java
  src/main/java/com/nbc/newsfeeds/domain/member/controller/ProfileController.java
  src/test/java/com/nbc/newsfeeds/domain/comment/service/CommentServiceTest.java
  src/test/java/com/nbc/newsfeeds/domain/feed/service/FeedServiceTest.java
  src/test/java/com/nbc/newsfeeds/domain/friend/service/FriendServiceUnitTest.java
Labels: bug

#82 Fix : 친구 게시글 조회 캐싱 로직 실수 수정
  src/main/java/com/nbc/newsfeeds/common/util/CursorPaginationUtil.java
Labels: bug

#81 Docs/readme
  README.md
  src/main/java/com/nbc/newsfeeds/domain/friend/repository/FriendCacheRepository.java
Labels: documentation

#84 Docs : README 수정
  README.md
Labels: documentation

#85 Fix : Friendship 인덱스 수정
  src/main/java/com/nbc/newsfeeds/domain/friend/entity/Friendship.java
Labels: enhancement
